### ISSUE TITLE
install tool should have a trailing slash in dest:

### ISSUE THREAD

**Issue by ClementJ35** [mablanco/ansible-antirootkits#4]
We need a trailing slash in [tasks/main.yml#L150](https://github.com/mablanco/ansible-antirootkits/blob/master/tasks/main.yml#L150)

Because if the folder doesn't exist, it creates a file named /usr/local/bin instead of /usr/local/bin/bin/shelldetect.py

The next step would be to check the presence of the folder /usr/local/bin

**Comment by mablanco** [comment]
Hi @ClementJ35 . You're right that /usr/local/bin may not exist in a system as it's not part of any standard (if I'm not mistaken) but the fact is that it's already present in the great majority of modern Unix based OSes and included in the PATH variable.

Do you have an example of such a case? Maybe it'd be better to check for the OS and install the tool in a proper directory depending on the OS. I'm not comfortable testing for /usr/local/bin existence, creating it and adding to the PATH variable. That would be out of the scope of this Ansible role. What do you think?

**Comment by ClementJ35** [comment]
Hi @mablanco . I had the case on a VM distributed by a company that totally powned /usr/local/ with their own folder tree.
As you said, ensuring that the destination folder exist may be out of scope.
But just adding the slash force ansible to consider /usr/local/bin/ as a folder. It will fail if the folder doesn't exist instead of creating a /usr/local/bin file.
I'm waiting for shell detector to work if playbook don't fail and the playbook to fail if shell detector won't work.

**Comment by mablanco** [comment]
Hi @ClementJ35. I see your point. I've already added the trailing slash to `/usr/local/bin`. Thanks for your contribution!
