### ISSUE TITLE
/etc/chkrootkit.conf does not exist on ubuntu 22.04

### ISSUE THREAD

**Issue by cbillen** [mablanco/ansible-antirootkits#8]
Runs fine except for chkrootkit where I get this error 

TASK [mablanco.antirootkits : chkrootkit | install tool from repo] ********************************************************************************************
ok: [xxx]

TASK [mablanco.antirootkits : chkrootkit | enable daily scheduled runs] ***************************************************************************************
fatal: [xxx]: FAILED! => {"changed": false, "msg": "Destination /etc/chkrootkit.conf does not exist !", "rc": 257}

**Comment by qs5779** [comment]
Same for Pop OS. On pop the file was moved to the /etc/chkrootkit directory

$ ls -l /etc/chkrootkit
total 4
-rw-r--r-- 1 root root 3762 Dec 23  2021 chkrootkit.conf
-rw-r--r-- 1 root root    0 Dec 23  2021 chkrootkit.ignore


Since my shop is all >= 22.04, in my playbook I worked around this with:

  tasks:
    - name: ensure file exists
      ansible.builtin.file:
        state: link
        path: /etc/chkrootkit.conf
        src: /etc/chkrootkit/chkrootkit.conf
        force: true
    - name: "Install and configure antirootkits"
      ansible.builtin.include_role:
        name: mablanco.antirootkits

**Comment by mablanco** [comment]
I'll check if this is related to the chkrootkit package itself or if it has something to do with the distributions you mentioned. Thanks for reporting!

**Comment by mablanco** [comment]
Looks like the path change took place in chkrootkit's version 0.55-4, included in Ubuntu 22.04LTS, as version 0.54-1 (from Ubuntu 21.10) still uses the old path. Now I have a path for a fix.

**Comment by mablanco** [comment]
I've uploaded a fix to support the new config file path in Ubuntu 22.04. Please @cbillen and @qs5779 have a try and let me know how it goes.

**Comment by mablanco** [comment]
Closing as there's been no reply for two weeks.
