### ISSUE TITLE
mail recipient variable missmatch

### ISSUE THREAD

**Issue by peedy2495** [mablanco/ansible-antirootkits#9]
the mail recipient variable is defined as `antirootkits_mail_rcpt` in _default/main.yml_.
This variable is unused in the whole project.
But the variable `antirootkits_mail_to` is used in several tasks.

**Comment by mablanco** [comment]
Looks like I forgot to also change the variable in that file: https://github.com/mablanco/ansible-antirootkits/commit/1e7b51d32b79b34bdf9a65f9142eb4a192fe40db

I've just uploaded a fix. Thanks for pointing out!
